version: "3.7"
services:
  admin:
    build:
      context: ../
      dockerfile: app/admin/Dockerfile
    restart: always
    volumes:
      - ../log/admin:/home/comely-io/admin/log
      - ../storage:/home/comely-io/admin/storage
    environment:
      COMELY_APP_DEBUG: true
      COMELY_APP_CACHED_CONFIG: true
    env_file:
      - .env
    ports:
      - "${ADMIN_PORT}:6000"
    networks:
      comely-app-net:
        ipv4_address: 10.0.20.11
  api:
    build:
      context: ../
      dockerfile: app/api/Dockerfile
    restart: always
    volumes:
      - ../log/api:/home/comely-io/api/log
      - ../storage:/home/comely-io/api/storage
    environment:
      COMELY_APP_CACHED_CONFIG: true
    env_file:
      - .env
    ports:
      - "${API_PORT}:6000"
    networks:
      comely-app-net:
        ipv4_address: 10.0.20.12

# Networks Configuration
networks:
  comely-app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.20.0/27
