# Cipher Configuration
# ---
# If changed, project WILL STOP working, there is NO WAY AROUND if keys are lost or changed!
# Do NOT change these keys at ANY POINT AFTER INITIALISATION OF PROJECT! DO NOT!

# Primary Cipher Key
primary: "Primary Cipher Key"
# Secondary Key
secondary: "Secondary Key"
# Users models encryption
users: "Users models encryption"
# Project models encryption
project: "Project models encryption"
# Misc encryption
misc: "Misc encryption"
